Insert into ORIENTATION (ORIENTATION_ID,ORIENTATION_NAME) values (1,'HETEROSEXUAL');
Insert into ORIENTATION (ORIENTATION_ID,ORIENTATION_NAME) values (2,'HOMOSEXUAL');
Insert into ORIENTATION (ORIENTATION_ID,ORIENTATION_NAME) values (3,'BISEXUAL');